### ISSUE TITLE
FSH Finder should be updated daily

### ISSUE THREAD

**Issue by cmoesel** [FSHSchool/fsh-finder#3]
FSH Finder is awesome.  So awesome.  Thank you for this, @masnick.

I think it would be pretty swell if FSH Finder was updated daily.  Have you considered creating a GitHub action to build FSH Finder automatically?  I think you could use the [schedule trigger](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#onschedule) to get it to do this on a regular basis (and my suggestion would be daily).

**Comment by masnick** [comment]
Due to the long runtime of the script to update FSH Finder, GitHub Actions may not work with daily updates because we may exceed the free Actions allotment. I don't think it's possible to make the update script faster due to GitHub API rate limits.

For now daily updates are running automatically on a separate VM. We may want to revisit GitHub actions for long-term sustainability, but for now we do at least have regular automatic updates!

**Comment by cmoesel** [comment]
Automatic updates is what I was hoping for.  How they happen is less important!  I just suggested GitHub Actions because it's easy and free -- but I didn't think about the fact that it's only free up to a certain point!  Sounds like a separate VM will get the job done.  Thanks, Max!
